server:
  port: 9003
eureka:
  client:
    #registerWithEureka: false  如何不要注册成服务用此配置，并且把instance相关的注释掉
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:

    instance-id: user-0 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 30 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: sc-user #此实例注册到eureka服务端的name
  zipkin:
    base-url: http://localhost:9007  #指定Zipkin server地址
    sleuth:
      sampler:
        probability: 1.0
feign:
  hystrix:
    enabled: true #远程调用熔断

management:
  endpoints:
    web:
      exposure:
        include: '*'
